spring:
  profiles:
    active:
    - dev
  application:
    name: consumer
    version: v1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/consumer
    username: root
    password: 123
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
  flyway:
    locations: classpath:db/migration
    baselineOnMigrate: true
  redis:
    host: 192.168.175.135
    port: 6379
    database: 0  # 连接0号库
    timeout: 60s  # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    jedis:  # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
      pool:
        max-idle: 500  # 最大空闲连接数
        min-idle: 50  # 最小空闲连接数
        max-wait:  -1s  # 等待可用连接的最大时间，负数为不限制
        max-active: -1  # 最大活跃连接数，负数为不限制

server:
  servlet:
    contextPath: /${spring.application.name}/${spring.application.version}
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    
---
spring:
  profiles: dev
  
server:
  port: 9001

eureka:
  client:
    service-url:
      defaultZone: http://eureka1.cloud.com:8001/eureka/

---
spring:
  profiles: sit
  
server:
  port: 9002

eureka:
  client:
    service-url:
      defaultZone: http://eureka1.cloud.com:8002/eureka/
  