spring:
  profiles:
    active:
    - dev

---
spring:
  profiles: dev
  
server:
  port: 8001
  
eureka:
  instance:
    hostname: eureka1.cloud.com
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

---
spring:
  profiles: sit
  
server:
  port: 8002
  
eureka:
  instance:
    hostname: eureka1.cloud.com
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
