server:
  port: 8802
  time: update 99999999

spring:
  application:
    name: service-user
management: 
  endpoints:
    web:
      exposure: 
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*" 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/